# Generated by Django 4.2 on 2023-04-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newegg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('address', models.CharField(default='no address', max_length=100)),
                ('email', models.CharField(default='no email', max_length=100)),
                ('phone_number', models.CharField(default='no phonenumber', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to='newegg.customer'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to='newegg.customer'),
        ),
    ]
