# Generated by Django 4.2 on 2023-04-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newegg', '0003_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='shopping_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='newegg.shoppingcart'),
        ),
    ]
