# Generated by Django 4.2 on 2023-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newegg', '0004_orderdetails_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(default='no description', max_length=300),
        ),
    ]
