# Generated by Django 4.2 on 2023-04-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newegg', '0005_alter_product_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
