# Generated by Django 4.2 on 2023-04-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newegg', '0008_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
