# Generated by Django 4.2 on 2023-04-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newegg', '0012_customer_remove_orderdetails_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='name',
        ),
    ]
